namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP

livenessProbePath: /healthz
livenessProbePort: 3111
readinessProbePath: /healthz
readinessProbePort: 3111

deployment:
  replicaCount: 5
  containerPort: 3111
  resources:
    requests:
      memory: 128Mi
      cpu: 350m
    limits:
      memory: 256Mi
      cpu: 500m

image:
  repository: rfrodriguez/techtrends
  tag: latest
  pullPolicy: Always 
