namespace:
  name: staging 

service:
  port: 5111
  targetPort: 3111
  protocol: TCP

deployment:
  replicaCount: 3
  containerPort: 3111
  livenessProbe:
    path: /healthz
  readinessProbe:
    path: /healthz
  resources:
    requests:
      memory: 90Mi
      cpu: 350m
    limits:
      memory: 128mi 
      cpu: 500m

image:
  repository: rfrodriguez/techtrends
  tag: latest
  pullPolicy: IfNotPresent
