namespace:
  name: staging 

service:
  port: 5111
  targetPort: 3111
  protocol: TCP

livenessProbePath: /healthz
livenessProbePort: 3111
readinessProbePath: /healthz
readinessProbePort: 3111

deployment:
  replicaCount: 3
  containerPort: 3111
  resources:
    requests:
      memory: 90Mi
      cpu: 350m
    limits:
      memory: 128Mi
      cpu: 500m

image:
  repository: rfrodriguez/techtrends
  tag: latest
  pullPolicy: IfNotPresent
