namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP

deployment:
  replicaCount: 5
  containerPort: 3111
  livenessProbe:
    path: /healthz
  readinessProbe:
    path: /healthz
  resources:
    requests:
      memory: 128Mi
      cpu: 350m
    limits:
      memory: 256Mi
      cpu: 500m

image:
  repository: rfrodriguez/techtrends
  tag: latest
  pullPolicy: Always 
